repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.96.1
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_tflint
      - id: terraform_checkov
        args:
          - --args=--quiet
          - --args=--skip-check CKV_AWS_18
          - --args=--skip-check CKV_AWS_115
          - --args=--skip-check CKV_AWS_116
          - --args=--skip-check CKV_AWS_144
          - --args=--skip-check CKV_AWS_272
      - id: terraform_tfsec
        args:
          - >
            --args=--no-color
            -e "aws-s3-enable-bucket-logging"